### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by icidasset** [icidasset/ongaku-ryoho#18]
Things to do before "launching":

- [x] Add 'hold shift key to remove track from collection' (ie. when in a, non-special, collection)
- [x] Find a way to explain the 'hold shift to add track to collection' and 'hold alt to add to queue' actions
- [x] Add a better introduction (how to use the app) -> when there are no tracks (1st screen after sign up)
- [x] Add production build and deploy command
- [x] Add some more content to the about page, so people actually know what this thing is
- [x] Extend README
- [x] #16 
- [x] #19 
- [x] Make new user and test everything again
- [x] Do browser checks again
